/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package belegaufgabe;

import org.junit.Test;

public class AppTest {
    @Test public void appHasAGreeting() {
        new App();
    }
}
